taiki-e/portable-atomic

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
README.md
build.rs
src/imp/aarch64.rs
src/imp/mod.rs
src/int.rs
src/lib.rs
tools/build.sh

This supports 128-bit atomics for aarch64 at Rust 1.59+. This was previously supported only on nightly.

Support 128-bit atomics for aarch64 on stable

---

README.md
bench/benches/bench.rs
src/imp/atomic128/cpuid.rs
src/imp/atomic128/x86_64.rs

x86_64 part of #10
The following are the results of a simple microbenchmark:
```
bench_portable_atomic_arch/u128_load
time:   [1.4598 ns 1.4671 ns 1.4753 ns]
change: [-81.510% -81.210% -80.950%] (p = 0.00 < 0.05)
Performance has improved.
Found 7 outliers among 100 measurements (7.00%)
1 (1.00%) low mild
4 (4.00%) high mild
2 (2.00%) high severe
bench_portable_atomic_arch/u128_store
time:   [1.3852 ns 1.3937 ns 1.4024 ns]
change: [-82.318% -81.989% -81.621%] (p = 0.00 < 0.05)
Performance has improved.
Found 10 outliers among 100 measurements (10.00%)
3 (3.00%) low mild
5 (5.00%) high mild
2 (2.00%) high severe
bench_portable_atomic_arch/u128_concurrent_load
time:   [56.422 us 56.767 us 57.204 us]
change: [-70.807% -70.143% -69.443%] (p = 0.00 < 0.05)
Performance has improved.
Found 9 …
```

Use SSE for 128-bit atomic load/store on Intel CPU with AVX

---

src/imp/atomic128/aarch64.rs
src/imp/atomic128/macros.rs
src/imp/atomic128/s390x.rs
src/imp/atomic128/x86_64.rs
src/imp/fallback/imp.rs
src/imp/fallback/mod.rs
src/imp/fallback/seq_lock.rs

Based on the code generated for DW RMWs by LLVM.
Currently, the first load is done by cmpxchg16b, which is not efficient because it means that cmpxchg16b is called at least twice. (although it is actually fast enough in some cases because we use a hack that assumes initial values)

x86_64: Use byte-wise atomic load for first load in 128-bit RMWs

---

CHANGELOG.md
Cargo.toml
README.md
build.rs
src/lib.rs
src/tests/helper.rs

This provides stable equivalent of [`#![feature(strict_provenance_atomic_ptr)]`](https://github.com/rust-lang/rust/issues/99108).
- `AtomicPtr::fetch_ptr_{add,sub}`
- `AtomicPtr::fetch_byte_{add,sub}`
- `AtomicPtr::fetch_{or,and,xor}`
These APIs are compatible with strict-provenance on `cfg(miri)`.
Otherwise, they are compatible with permissive-provenance.
Once `#![feature(strict_provenance_atomic_ptr)]` is stabilized, these APIs will be strict-provenance compatible in all cases from the version in which it is stabilized.
(This is also a generalization of what [I did in crossbeam-epoch](https://github.com/crossbeam-rs/crossbeam/pull/796).)

Provide stable equivalent of #![feature(strict_provenance_atomic_ptr)]

---

CHANGELOG.md
README.md
src/lib.rs
src/tests/helper.rs

This provides stable equivalent of [`#![feature(atomic_bool_fetch_not)]`](https://github.com/rust-lang/rust/issues/98485).
- `AtomicBool::fetch_not`

Provide stable equivalent of #![feature(atomic_bool_fetch_not)]

---

.cirrus.yml
CHANGELOG.md
bench/benches/bench.rs
src/imp/atomic128/aarch64.rs

See https://github.com/llvm/llvm-project/issues/55199 for the motivation.
In CAS we have already done this; in RMW and store we still use LDXP/STXP even if LSE is available because [the performance benefits do not seem clear yet](https://github.com/taiki-e/portable-atomic/pull/20#issuecomment-1204208980).

aarch64: Use CASP instead of LDXP/STXP for load if available

---

CHANGELOG.md
README.md
src/imp/interrupt/mod.rs
src/imp/mod.rs
src/imp/msp430.rs
src/lib.rs
tools/build.sh

This previously required unsafe cfg `portable_atomic_unsafe_assume_single_core`, but since all MSP430 and AVR are single-core, we can safely provide atomic CAS based on disabling interrupts.
Thanks @cr1901 for pointing out this in https://github.com/pftbest/msp430-atomic/pull/6#issuecomment-1212675977.

Always provide atomic CAS for MSP430 and AVR

---

CHANGELOG.md
README.md
src/imp/interrupt/armv4t.rs
src/imp/interrupt/mod.rs
src/imp/mod.rs
src/lib.rs
tests/gba/.cargo/config.toml
tests/gba/Cargo.toml
tests/gba/linker.ld
tests/gba/src/main.rs
tools/build.sh
tools/no-std.sh

Closes #26 
This currently disables only IRQs. This is explained in the document on safety requirements:
> - On pre-v6 ARM, this currently disables only IRQs.
>   Enabling this cfg in an environment where FIQs must also be disabled is also considered **unsound**.
I have a few questions:
- ~~Should we also disable FIQs? [The emulation of atomic operation on Linux seemed to disable only IRQs](https://github.com/torvalds/linux/blob/eb555cb5b794f4e12a9897f3d46d5a72104cd4a7/arch/arm/include/asm/atomic.h#L156-L170), but they may have disabled FIQs globally.~~ EDIT: see https://github.com/taiki-e/portable-atomic/pull/28#issuecomment-1214146912
- Is there a way to test this target on CI?

interrupt: Support no-std pre-v6 ARM targets

---

CHANGELOG.md
src/imp/interrupt/armv4t.rs
src/imp/interrupt/armv6m.rs
src/imp/interrupt/mod.rs
src/imp/interrupt/msp430.rs
src/imp/interrupt/riscv.rs
src/imp/msp430.rs

Since pre-v6[^v6] ARM has no Data Memory Barrier and cannot implement atomic in a way compatible with v6 and later multicore CPUs without OS helpers, LLVM generates libcalls for atomic operations that require synchronization, such as Acquire/Release and SeqCst.
Currently, (when `portable_atomic_unsafe_assume_single_core` cfg is used) we consider this as "atomic load/store are not available on pre-v6 ARM" and always disable interrupts. However, relaxed load+compiler fence can do this more efficiently since we know it is single-core.
https://github.com/taiki-e/portable-atomic/blob/e6e1500f440e6a79d87f4471924c5e6613594b51/src/imp/interrupt/mod.rs#L34-L35
https://github.com/taiki-e/portable-atomic/blob/e6e1500f440e6a79d87f4471924c5e6613594b51/src/imp/interrupt/mod.rs#L23-L29
FYI @Lokathor …

Optimize pre-v6 ARM load/store on single-core systems

---

Cargo.toml
bench/version.rs
build.rs
portable-atomic-util/Cargo.toml
portable-atomic-util/LICENSE-APACHE
portable-atomic-util/LICENSE-MIT
portable-atomic-util/README.md
portable-atomic-util/build.rs
portable-atomic-util/src/lib.rs
portable-atomic-util/version.rs
version.rs

This adds an empty crate named `portable-atomic-util`.
For now, I'm considering putting the features proposed in #1 (#8) and #37 into this crate, but they may be merged into the main `portable-atomic` crate in the future.

Add empty portable-atomic-util crate

---

portable-atomic-util/src/arc.rs
portable-atomic-util/src/lib.rs
tools/build.sh

This pull requests resolves #37 by adding `Arc` and `Weak` types to the `portable-atomic-util` crate that use `portable_atomic::AtomicUsize` in their operation. The goal is to allow for portable using of `Arc` on platforms that may have allocation but not atomics. Arduino AVR comes to mind for this.
These new types are based off of the ones in `libstd`, but I explicitly avoid using unstable features. I do not implement unstable functions, like `new_uninit`. I also avoided certain functions like `new_cyclic` and `take_mut` because I didn't get around to it.

Add a reference counted container

---

README.md
src/imp/interrupt/README.md
src/imp/interrupt/armv4t.rs
src/imp/interrupt/armv6m.rs
src/imp/interrupt/mod.rs
src/imp/interrupt/riscv.rs
src/lib.rs
tools/build.sh

- Support RISC-V supervisor mode under `portable_atomic_s_mode` cfg
> On RISC-V without A-extension, this generates code for machine-mode (M-mode) by default. If you pass the `--cfg portable_atomic_s_mode` together, this generates code for supervisor-mode (S-mode). In particular, `qemu-system-riscv*` uses [OpenSBI](https://github.com/riscv-software-src/opensbi) as the default firmware.
- Support disabling FIQs on pre-v6 ARM under `portable_atomic_disable_fiq` cfg
> On pre-v6 ARM, this disables only IRQs by default. For many systems (e.g., GBA) this is enough. If the system need to disable both IRQs and FIQs, you need to pass the `--cfg portable_atomic_disable_fiq` together.
- Interrupt-related documentation improvements
- [README.md](https://github.com/taiki-e/portable-atomic/blob/18961fab …

interrupt: Various improvements

---

CHANGELOG.md
src/imp/atomic128/cpuid.rs
src/imp/atomic128/x86_64.rs

As mentioned in https://github.com/taiki-e/portable-atomic/issues/10#issuecomment-1345481599, AMD is also going to guarantee this.
Refs: https://gcc.gnu.org/bugzilla//show_bug.cgi?id=104688#c10

Use SSE for 128-bit atomic load/store on AMD CPU with AVX

---

.cspell.json
CHANGELOG.md
src/imp/mod.rs
target-specs/avr-unknown-gnu-atmega168.json
target-specs/msp430-unknown-none-elf.json
tools/build.sh

- Fix build error when not using `portable_atomic_unsafe_assume_single_core` cfg on AVR and MSP430 custom targets.
Since 0.3.11, atomic CAS was supported without the cfg on AVR and MSP430 builtin targets, but that change was not applied to custom targets.

Improve support for AVR and MSP430 custom targets

---

build.rs
src/imp/mod.rs
src/lib.rs
src/tests/helper.rs
tools/build.sh

Tested on x86_64-unknown-linux-gnu and aarch64-unknown-linux-gnu.
```sh
cargo update -p serde --precise=1.0.103
cargo update -p serde_test --precise=1.0.103
cargo update -p syn --precise=1.0.90
cargo update -p proc-macro2 --precise=1.0.43
cargo +nightly-2020-06-21 test --all-features # has unstable asm
cargo +nightly-2020-06-20 test --all-features # no unstable asm
```
Note: Old nightly compilers are essentially fragile, so support for them is on a best-effort basis.

Improve support for very old nightly

---

build.rs
src/imp/mod.rs
src/lib.rs
src/tests/helper.rs
tools/build.sh

If it is specified multiple times, the last value will be preferred.
```rust
// build.rs
use std::env;
fn main() {
println!("cargo:rerun-if-env-changed=PREFER_FIRST");
if env::var_os("PREFER_FIRST").is_some() {
if is_allowed_feature1("core_intrinsics") {
println!("cargo:rustc-cfg=core_intrinsics");
}
if is_allowed_feature1("asm_const") {
println!("cargo:rustc-cfg=asm_const");
}
} else {
if is_allowed_feature2("core_intrinsics") {
println!("cargo:rustc-cfg=core_intrinsics");
}
if is_allowed_feature2("asm_const") {
println!("cargo:rustc-cfg=asm_const");
}
}
}
fn is_allowed_feature1(name: &str) -> bool {
if let Some(rustflags) = env::var_os("CARGO_ENCODED_RUSTFLAGS") {
for mut flag in rustflags.to_string_lossy().split('\x1f') {
flag = flag.strip_prefix("-Z").unwrap_or(flag);
if let …
```

Fix `-Z allow-features` check

---

.github/workflows/ci.yml
CHANGELOG.md
src/imp/atomic128/aarch64.rs
src/imp/atomic128/intrinsics.rs
src/imp/atomic128/macros.rs
src/imp/atomic128/powerpc64.rs
src/imp/atomic128/s390x.rs
src/imp/atomic128/x86_64.rs
src/imp/core_atomic.rs
src/imp/fallback/imp.rs
src/imp/float.rs
src/imp/interrupt/mod.rs
src/imp/mod.rs
src/imp/msp430.rs
src/imp/x86.rs
src/lib.rs
src/tests/helper.rs
tests/api-test/src/helper.rs

Part of #48
- Add `AtomicI*::{fetch_neg,neg}` and `AtomicF*::fetch_neg` methods.
`AtomicI*::neg` are equivalent to the corresponding `fetch_*` methods, but do not return the previous value. They are intended for optimization on platforms that have atomic instructions for the corresponding operation, such as x86's `lock neg`.
Currently, optimizations by these methods (`neg`) are only guaranteed for x86.
- Add `Atomic{I,U}*::{fetch_not,not}` methods.
`Atomic{I,U}*::not` are equivalent to the corresponding `fetch_*` methods, but do not return the previous value. They are intended for optimization on platforms that have atomic instructions for the corresponding operation, such as x86's `lock not`, MSP430's `inv`.
Currently, optimizations by these methods (`not`) are only guaranteed for x86 …

Add fetch_neg/neg/fetch_not/not

---

.github/.cspell/project-dictionary.txt
.github/workflows/ci.yml
tests/riscv/.cargo/config.toml
tests/riscv/Cargo.toml
tests/riscv/build.rs
tests/riscv/link32.ld
tests/riscv/link64.ld
tests/riscv/src/main.rs
tools/no-std.sh

Currently, CI for these targets is build-only. Some code has already been tested on riscv64-linux and riscv32-linux, but interrupt-related code cannot be tested with user-mode.

Test no-std RISC-V targets with QEMU on CI

---

.cirrus.yml
CHANGELOG.md
Cargo.toml
README.md
bench/Cargo.toml
build.rs
src/imp/atomic128/aarch64.rs
src/imp/atomic128/cpuid.rs
src/imp/atomic128/x86_64.rs
src/lib.rs
src/tests/mod.rs
tools/build.sh

This enables `outline-atomics` feature by default and provides `portable_atomic_no_outline_atomics` cfg to disable it.
(outline-atomics enables several optimizations on x86_64 and aarch64. See [this list](https://github.com/taiki-e/portable-atomic/issues/10#issuecomment-1159368067) for details.)
It has previously been pointed out that due to the nature of the cargo feature, controlling this based on the cargo feature does not work well. Since this release, `outline-atomics` feature has been no-op, and outline-atomics is enabled by default.
Note: outline-atomics in portable-atomics is currently for 128-bit atomics. outline-atomics for atomics with other sizes is controlled by LLVM's `outline-atomics` target feature.
Closes #25

Enable outline-atomics by default and provide cfg to disable it

---

.github/.cspell/project-dictionary.txt
.github/.cspell/rust-dependencies.txt
.github/workflows/ci.yml
Cargo.toml
README.md
src/imp/float.rs
src/imp/interrupt/mod.rs
src/imp/mod.rs
src/imp/msp430.rs
src/imp/riscv.rs
src/lib.rs
src/tests/critical_section_std.rs
src/tests/mod.rs
tools/build.sh

I want to depreecate `atomic-polyfill` in favor of `portable-atomic`. This is the only thing left that `portable-atomic` can't do, so here it goes.
PR is still missing updating docs. I'll do it if you confirm you're onboard with the idea of supporting using `critical-section`.

Add Cargo feature to use critical-section.

---

CHANGELOG.md
src/imp/atomic128/aarch64.rs
src/imp/atomic128/intrinsics.rs
src/imp/atomic128/macros.rs
src/imp/atomic128/powerpc64.rs
src/imp/core_atomic.rs

Replace CAS loop with fetch_xor(-1i*)/fetch_xor(u*::MAX).

Optimize Atomic{I,U}*::{fetch_not,not}

---

.github/bors.toml
.github/workflows/ci.yml
build.rs
src/imp/atomic128/README.md
src/imp/atomic128/aarch64.rs
src/imp/atomic128/intrinsics.rs
tools/build.sh

Follow-up #20
In #20, we postponed this (https://github.com/taiki-e/portable-atomic/pull/20#issuecomment-1204208980), but LLVM 16+ adopted this (https://github.com/llvm/llvm-project/commit/10d34f5538e0d231a172608bdb7d08824771c7c7), so we'll follow LLVM's behavior.

aarch64: Use CASP instead of LDXP/STXP for store/RMW if available

---

.github/.cspell/project-dictionary.txt
src/imp/atomic128/aarch64.rs
src/imp/atomic128/detect/aarch64_macos.rs
src/imp/atomic128/detect/aarch64_windows.rs
src/lib.rs

This module is currently only enabled on tests because aarch64 macOS always supports FEAT_LSE and FEAT_LSE2.
If macOS supporting Armv9.4-a becomes popular in the future, this module will be used to support outline atomics for FEAT_LSE128/FEAT_LRCPC3.

detect: Support run-time detection on aarch64 macOS (test-only)

---

build.rs
src/imp/atomic128/aarch64.rs
src/imp/atomic128/detect/aarch64_linux.rs
src/imp/atomic128/detect/aarch64_std.rs
src/imp/atomic128/detect/common.rs
src/lib.rs
target-specs/aarch64-unknown-linux-uclibc.json
tools/build.sh

Similar to https://github.com/taiki-e/portable-atomic/commit/3f5d42f70485fd022c2e4a847c81737e3651bbde.
This also supports building for aarch64 linux-uclibc.

aarch64: Support outline atomics on old nightly

---

.github/.cspell/project-dictionary.txt
src/imp/atomic128/detect/aarch64_linux.rs

Samsung Exynos 9810 has a bug that big and little cores have different ISAs. And on older Android (pre-9), the kernel incorrectly reports that features available only on some cores are available on all cores.
See https://reviews.llvm.org/D114523 for details.
Our own run-time detection code has not been released yet and is not a problem, but portable-atomic < 1.1 may have been affected by this issue since rustc 1.69-nightly when is_aarch64_feature_detected supported run-time detection on Android. (https://github.com/rust-lang/stdarch/pull/1351, https://github.com/rust-lang/rust/pull/105784)
A patch on stdarch side: https://github.com/rust-lang/stdarch/pull/1378

detect: Workaround Exynos 9810 bug on aarch64 Android

---

README.md
bench/benches/imp/spinlock_fallback.rs
build.rs
src/imp/atomic128/intrinsics.rs
src/imp/atomic128/macros.rs
src/imp/core_atomic.rs
src/imp/fallback/imp.rs
src/imp/fallback/utils.rs
src/imp/float.rs
src/imp/interrupt/mod.rs
src/imp/riscv.rs
src/imp/x86.rs
src/lib.rs
src/tests/helper.rs
src/utils.rs

> Returns a mutable pointer to the underlying {bool,pointer,integer,float}.
>
> Returning an `*mut` pointer from a shared reference to this atomic is safe because the atomic types work with interior mutability. Any use of the returned raw pointer requires an `unsafe` block and has to uphold the safety requirements:
> - If this atomic type is [lock-free](Self::is_lock_free), any concurrent operations on it must be atomic.
> - Otherwise, any concurrent operations on it must be compatible with operations performed by this atomic type.
>
> This is `const fn` on Rust 1.58+.

Expose as_ptr

---

README.md
bench/benches/bench.rs
build.rs
src/imp/atomic128/README.md
src/imp/atomic128/detect/x86_64.rs
src/imp/atomic128/x86_64.rs
src/imp/fallback/imp.rs
src/imp/fallback/mod.rs
src/imp/fallback/seq_lock.rs
src/imp/mod.rs
src/lib.rs
src/tests/mod.rs
src/utils.rs

cmpxchg16b_target_feature has been stabilized in https://github.com/rust-lang/rust/pull/106774.

x86_64: Update to stabilized cmpxchg16b_target_feature

---

.github/.cspell/project-dictionary.txt
.github/workflows/ci.yml
CHANGELOG.md
bench/benches/imp/spinlock_fallback.rs
build.rs
src/imp/atomic128/intrinsics.rs
src/imp/atomic128/macros.rs
src/imp/core_atomic.rs
src/imp/fallback/imp.rs
src/imp/interrupt/mod.rs
src/imp/x86.rs
src/lib.rs
src/tests/helper.rs
src/utils.rs

They correspond to x86's `lock bt{s,r,c}`, and the implementation calls them on x86/x86_64.
> LLVM 14 and older don't support generating `lock bt{s,r,c}`.
> https://godbolt.org/z/G1TMKza97
> LLVM 15 only supports generating `lock bt{s,r,c}` for immediate bit offsets.
> https://godbolt.org/z/dzzhr81z6
> LLVM 16 can generate `lock bt{s,r,c}` for both immediate and register bit offsets.
> https://github.com/taiki-e/portable-atomic/issues/48#issuecomment-1453473831
> So, use fetch_* based implementations on LLVM 16+, otherwise use asm based implementations.
Closes #48

Add bit_{set,clear,toggle} to Atomic{I,U}* and AtomicPtr

---

src/imp/atomic128/intrinsics.rs
src/imp/atomic128/s390x.rs
src/imp/atomic128/x86_64.rs
src/imp/core_atomic.rs
src/imp/float.rs
src/lib.rs
src/utils.rs

They are private functions and all closure instances only operate on the value loaded, so there is no need to synchronize the first load/failed CAS.
Unlike the public API's fetch_update, in these functions, there is no way to exit the loop until the CAS succeeds. i.e., only the value synchronized by a successful CAS with the specified order will be returned to the user.

Relax failure ordering in private CAS loop helpers

---

portable-atomic-util/CHANGELOG.md
portable-atomic-util/src/arc.rs

This fixes a [potential unsoundness recently found in the standard library's `Arc`](https://github.com/rust-lang/rust/issues/108706).

util: Prevent weak counter overflow in Arc::downgrade

---

.cirrus.yml
.github/.cspell/project-dictionary.txt
.github/bors.toml
.github/workflows/ci.yml
Cross.toml
bench/benches/bench.rs
src/imp/arm_linux.rs
src/imp/fallback/mod.rs
src/imp/mod.rs
src/lib.rs
src/tests/mod.rs
src/utils.rs
tools/build.sh

Currently, we are using fallback implementation for 64-bit atomics on pre-v6 ARM Linux/Android such as armv5te-unknown-linux-gnueabi and arm-linux-androideabi.
However, Linux kernel 3.1+ provides [kernel user helpers](https://www.kernel.org/doc/Documentation/arm/kernel_user_helpers.txt) for 64-bit atomics. This could be more efficient than a lock-based fallback implementation, because it calls native atomic instructions, depending on the actual CPU version.
This PR uses __kuser_cmpxchg64 on Linux kernel 3.1+, otherwise use fallback implementation as before.
Since Rust 1.64, the Linux kernel requirement for Rust when using std[^1] is [3.2+](https://blog.rust-lang.org/2022/08/01/Increasing-glibc-kernel-requirements.html#affected-targets), so it should be possible to omit the dynamic kernel …

Use __kuser_cmpxchg64 for 64-bit atomics on pre-v6 ARM Linux/Android

---

.github/.cspell/project-dictionary.txt
.github/workflows/ci.yml
CHANGELOG.md
README.md
src/imp/interrupt/README.md
src/imp/interrupt/mod.rs
src/imp/interrupt/xtensa.rs
src/imp/mod.rs
src/lib.rs
tests/api-test/src/helper.rs
tests/xtensa/.cargo/config.toml
tests/xtensa/Cargo.toml
tests/xtensa/build.rs
tests/xtensa/src/main.rs
tools/build.sh
tools/no-std.sh

This adds `portable_atomic_unsafe_assume_single_core` support for Xtensa targets without atomic CAS.

interrupt: Support Xtensa

---

portable-atomic-util/src/arc.rs

Forgot to add this when I was writing #41. Should hopefully improve symmetry between `std::sync::Arc` and `portable_atomic_util::Arc`.

feat: Implement AsRef and Borrow on Arc

---

portable-atomic-util/src/arc.rs

Split from #92 because it might be slightly more controversial. Implement `Unpin` on `Arc` for all `T`.

feat: Implement Unpin on Arc

---

.github/workflows/ci.yml
tools/build.sh

Except for targets where `core` cannot be built due to compiler bugs.
https://github.com/taiki-e/portable-atomic/blob/e88128ed5cc1f66e6b3ccd04ca987ac3472803c6/tools/build.sh#L343-L348

Check all builtin targets in CI

---

Cargo.toml
portable-atomic-util/Cargo.toml
src/lib.rs
tools/build.sh

Provide better error message if dependents require atomic CAS but the end user forgets to use single-core cfg or critical-section feature.
Context: https://github.com/mvdnes/spin-rs/issues/151
cc @zesterer
Enable require-cas feature on spin (https://github.com/taiki-e/spin-rs/commit/990fa92e5f0e4c751f7f171fa2123ef39449c9c6)
```diff
- portable-atomic = { version = "1", optional = true, default-features = false }
+ # Enable require-cas feature to provide a better error message if the end user forgets to use cfg.
+ portable-atomic = { version = "1", optional = true, default-features = false, features = ["require-cas"] }
```
Then, when building spin without single-core cfg or CS feature, the following error message will be displayed.
```console
$ cargo build --target thumbv6m-none-eabi …
```

Add require-cas feature

---

.github/.cspell/project-dictionary.txt
build.rs
src/imp/atomic128/README.md
src/imp/atomic128/aarch64.rs
tools/build.sh

armv9.4-a added the following instructions as FEAT_LSE128:
- LDCLRP(AL) -- 128-bit atomic bit clear: https://developer.arm.com/documentation/ddi0602/2022-12/Base-Instructions/LDCLRP--LDCLRPA--LDCLRPAL--LDCLRPL--Atomic-bit-clear-on-quadword-in-memory-?lang=en
- LDSETP(AL) -- 128-bit atomic bit set/or: https://developer.arm.com/documentation/ddi0602/2022-12/Base-Instructions/LDSETP--LDSETPA--LDSETPAL--LDSETPL--Atomic-bit-set-on-quadword-in-memory-?lang=en
- SWPP(AL) -- 128-bit atomic swap: https://developer.arm.com/documentation/ddi0602/2022-12/Base-Instructions/SWPP--SWPPA--SWPPAL--SWPPL--Swap-quadword-in-memory-?lang=en
armv8.9-a/armv9.4-a added the following instructions as FEAT_LRCPC3:
- LDIAPP -- 128-bit acquire-load: https://developer.arm.com/documentation/ddi0602/2022-09/Base-Instruct …

aarch64: Support FEAT_LSE128 and FEAT_LRCPC3

---

README.md
build.rs
src/imp/atomic128/aarch64.rs
src/lib.rs

Support outline-atomics on pre-1.61 rustc.
https://developer.arm.com/documentation/100067/0612/armclang-Integrated-Assembler/AArch32-Target-selection-directives?lang=en

aarch64: Use .arch_extension directive instead of #[target_feature]

---

.github/.cspell/project-dictionary.txt
.github/workflows/ci.yml
Cargo.toml
build.rs
src/imp/interrupt/README.md
src/imp/interrupt/mod.rs
src/imp/riscv.rs
src/lib.rs
src/utils.rs
tools/build.sh
tools/no-std.sh

> On RISC-V (without A-extension) with the `force-amo` feature, this uses AMO instructions for RMWs that have corresponding AMO instructions even if A-extension is disabled. For other RMWs, this disables interrupts as usual.
> Some operations don't require disabling interrupts (loads and stores on targets except for AVR, but additionally on MSP430 {8,16}-bit `add,sub,and,or,xor,not`, **on RISC-V with the `force-amo` feature 32-bit(RV32)/{32,64}-bit(RV64) `swap,fetch_{add,sub,and,or,xor,not,max,min},add,sub,and,or,xor,not` and {8,16}-bit `fetch_{and,or,xor,not},and,or,xor,not`**). However, when the `critical-section` feature is enabled, critical sections are taken for all atomic operations.
Closes #123
This feature requires Rust 1.72+ because `.option arch` requires it. …

Add force-amo feature (portable_atomic_force_amo cfg)

---

portable-atomic-util/src/arc.rs

Re-use the implementation of `Layout::padding_needed_for()` for offset alignment calculations. #138 did not properly account for non-power of two Header sizes - which admittedly matters little, but there's no reason to diverge from std here.

Amend Arc value offset calculation

---

.github/.cspell/project-dictionary.txt
.github/workflows/ci.yml
portable-atomic-util/build.rs
portable-atomic-util/src/arc.rs
portable-atomic-util/src/lib.rs
portable-atomic-util/tests/arc.rs
tools/build.sh
tools/test.sh

util: Rewrite Arc based on std::sync::Arc

---

portable-atomic-util/README.md
portable-atomic-util/build.rs
portable-atomic-util/src/arc.rs
portable-atomic-util/src/lib.rs
portable-atomic-util/src/task.rs

This is an equivalent to `std::task::Wake`, but using `portable_atomic_util::Arc` as a reference-counted pointer.
**Note:** Unlike `std::task::Wake`, all methods take `this:` instead of `self:`. This is because using `portable_atomic_util::Arc` as a receiver requires the unstable `arbitrary_self_types` feature.
This should allow crates like waker-fn to support targets without atomics.
FYI @notgull

util: Add task::Wake

---

CHANGELOG.md
README.md
build.rs
src/cfgs.rs
src/imp/atomic128/README.md
src/imp/atomic128/intrinsics.rs
src/imp/atomic128/x86_64.rs
src/imp/fallback/mod.rs
src/imp/mod.rs
src/lib.rs
src/tests/mod.rs

Unlike AArch64 and RISC-V, x86's assembler doesn't check instruction requirements for the currently enabled target features. In the first place, there is no option in the x86 assembly for such case, like ARM .arch_extension, RISC-V .option arch, PowerPC .machine, etc.
(However, we set target_feature(enable) when available (Rust 1.69+) in case a new codegen backend is added that checks for it in the future, or an option is added to the assembler to check for it.)

x86_64: Support run-time detection for cmpxchg16b on pre-1.69 rustc

---

README.md
src/lib.rs

Rust 1.78 requires Windows 10 (with a separate Win7 tier-3 target for Windows 7/8.1 support) and Windows 10 64-bit requires CMPXCHG16B. Because of this, Rust 1.78 now enables CMPXCHG16B for 64-bit Windows targets. This updates the documentation to reflect that.

Updated documentation to reflect that Windows x64 now enables CMPXCHG16B

---

.github/.cspell/project-dictionary.txt
src/imp/atomic128/README.md
src/imp/atomic128/aarch64.rs
src/imp/atomic128/detect/aarch64_aa64reg.rs
src/imp/atomic128/detect/aarch64_macos.rs
src/imp/atomic128/detect/auxv.rs
src/imp/atomic128/detect/common.rs

- (new) If FEAT_LSE2 is not available at compile-time, we want to do run-time detection of FEAT_LSE2 (we are already doing this as it greatly improves performance: https://github.com/taiki-e/portable-atomic/pull/126), so we do run-time detection of FEAT_LRCPC3/FEAT_LSE128 at the same time.
- (as-is) If FEAT_LSE2 is available at compile-time, we don't do run-time detection of FEAT_LRCPC3/FEAT_LSE128 *for load/store* at this time, since FEAT_LRCPC3/FEAT_LSE128 is not yet available for most CPUs.
(macOS that doesn't have any FEAT_LRCPC3/FEAT_LSE128-enabled CPUs as of M4 is only a platform that currently enables FEAT_LSE2 at compile-time by default.)
- (as-is) We don't do run-time detection of FEAT_LSE128 *for swap/fetch_and/fetch_or* at this time, because FEAT_LSE128 is not yet available for …

aarch64: Enable run-time detection of FEAT_LRCPC3/FEAT_LSE128 in load/store

---

.github/.cspell/project-dictionary.txt
build.rs
src/imp/atomic128/aarch64.rs
tools/build.sh

LLVM supports FEAT_LRCPC3/FEAT_LSE128 instructions on LLVM 16+, so use .inst directive on old LLVM. https://github.com/llvm/llvm-project/commit/a6aaa969f7caec58a994142f8d855861cf3a1463 https://github.com/llvm/llvm-project/commit/7fea6f2e0e606e5339c3359568f680eaf64aa306
AAarch64 .inst directive is portable since LLVM 7: https://github.com/llvm/llvm-project/commit/3e3d39d07ea8bc210dfb256edc0ac5c66fb84474

aarch64: Support FEAT_LRCPC3/FEAT_LSE128 with pre-16 LLVM

---

build.rs
src/lib.rs

Closes #180 
See #180 for details.

Improve diagnostics when method that requires CAS is unavailable using #[diagnostic::on_unimplemented]

---

.github/.cspell/project-dictionary.txt
.github/workflows/ci.yml
build.rs
src/cfgs.rs
src/imp/atomic128/README.md
src/imp/atomic128/macros.rs
src/imp/atomic128/riscv64.rs
src/imp/atomic64/README.md
src/imp/atomic64/macros.rs
src/imp/atomic64/riscv32.rs
src/imp/detect/common.rs
src/imp/detect/riscv_linux.rs
src/imp/fallback/mod.rs
src/imp/mod.rs
src/imp/riscv.rs
src/lib.rs
src/tests/mod.rs
src/utils.rs
tools/build.sh

This supports 128-bit atomics for riscv64 and 64-bit atomics for riscv32 with [Zacas extension](https://github.com/riscv/riscv-isa-manual/blob/riscv-isa-release-8b9dc50-2024-08-30/src/zacas.adoc) (ratified more than half a year ago) enabled.
Note:
- Currently Zacas extension support is marked as experimental in LLVM: so `-C target-feature=+experimental-zacas` instead of `-C target-feature=+zacas` is needed for now.
- As the name indicates, support for this extension on our part at this time will also be somewhat experimental.
- ~~Perhaps we cannot merge this PR until LLVM marks this as non-experimental.~~
- Now marked as experimental on our end too. And now only enabled for LLVM 19 because it is more experimental in LLVM 17/18 and "experimental-zacas" feature may no longer exist when it …

riscv: Support 128-bit atomics for RV64 and 64-bit atomics for RV32 (Zacas extension)

---

src/imp/atomic128/aarch64.rs
src/imp/detect/README.md
src/imp/detect/aarch64_illumos.rs
src/imp/detect/common.rs
tools/build.sh

aarch64 port of illumos support run-time detection of FEAT_LSE and FEAT_LSE2 using getisax.
Note that aarch64 port is not yet available in main [illumos/illumos-gate](https://github.com/illumos/illumos-gate) tree. It is available in [richlowe/illumos-gate](https://github.com/richlowe/illumos-gate).
We need to decide how to handle this potential unstability. ~~(For example, mark it as experimental and disable run-time detection on this platform by default.)~~ For now, disabled run-time detection on this platform by default as aarch64 port is experimental.

detect: Support run-time detection on AArch64 illumos

---

src/cfgs.rs
src/imp/float.rs
src/imp/riscv.rs
src/lib.rs
src/utils.rs
tools/build.sh

Addresses https://github.com/taiki-e/portable-atomic/issues/123#issuecomment-2369371683
cc @romancardenas

riscv: Support RMW when zaamo enabled (even when unsafe-assume-single-core disabled)

---

.github/.cspell/project-dictionary.txt
.github/workflows/ci.yml
tests/msp430/.cargo/config.toml
tests/msp430/Cargo.toml
tests/msp430/build.rs
tests/msp430/memory.x
tests/msp430/src/main.rs
tools/build.sh
tools/mspdebug-test-runner.sh
tools/no-std.sh

Except for the fact that I [split the test into 10+ runs due to size (still not enough to run the float test)](https://github.com/taiki-e/portable-atomic/blob/03220a72980d7d77c66d5a291ca9724ff6da046e/tools/no-std.sh#L287-L292), and that I had to use a [runner helper](https://github.com/taiki-e/portable-atomic/blob/03220a72980d7d77c66d5a291ca9724ff6da046e/tools/mspdebug-test-runner.sh) like the ones used in armv4t, this is generally the same as the tests for the other targets and It is the same and can be run on CI.
```
(mspdebug) run
Running. Press Ctrl+C to interrupt...
starting tests...
test test_atomic_i8 ... ok
test test_atomic_u8 ... ok
Tests finished successfully
```
(There may be a way to handle the size issue better, but I have not had time to investigate it sufficiently.)
Closes …

tests: Test MSP430 using mspdebug

---

.github/dependabot.yml
Cargo.toml

Hope this will fix CI build in PR #196 etc.

CI: pin libc in dev-dependencies for Rust pre-1.63

---

.github/workflows/ci.yml

coming from this comment: https://github.com/taiki-e/portable-atomic/pull/195#discussion_r1837022080
> These are heavy to always be enabled, but they will be temporarily uncommented to see if they are affected by the LLVM bug if the code for this target is changed.
If we need some more info in these comments, I would appreciate any pointers to what LLVM issue(s) this is related to.

add CI comments related to commented-out LLVM version entries in test matrix

---

.github/.cspell/project-dictionary.txt
.github/workflows/ci.yml
Cargo.toml
portable-atomic-util/CHANGELOG.md
portable-atomic-util/README.md
portable-atomic-util/build.rs
portable-atomic-util/src/arc.rs
portable-atomic-util/src/lib.rs
portable-atomic-util/tests/arc.rs

_(with some minor CI & documentation updates)_
Adapted from Rust std library - this adds automatic casting to Arc<Trait> as discussed in issue #143 behind `portable_atomic_unstable_coerce_unsized` cfg option ... of course this would only work with Rust nightly until custom unsized coercions is stabilized ref: https://github.com/rust-lang/rust/issues/18598
MOTIVATION: enable more straight-forward support for `rustls` on `no-std` targets without built-in atomics ref: https://github.com/rustls/rustls/issues/2068 (using an internal alias as an easy way to select between `alloc::sync::Arc` vs `portable_atomic_util::Arc` as needed) _as @brodycj has proposed now in rustls/rustls#2200_
__P.S.__ IIRC I think I have seen a lot of the smaller embedded CPU targets more likely to be built with Rust …

util: add portable_atomic_unstable_coerce_unsized cfg option

---

.cirrus.yml
.github/workflows/ci.yml
Cargo.toml
README.md
src/imp/float/int.rs
src/imp/float/mod.rs
src/lib.rs
src/tests/helper.rs
src/tests/mod.rs
src/utils.rs
tests/api-test/src/helper.rs
tests/api-test/src/lib.rs
tools/build.sh

- When both Cargo feature `float` and unstable `--cfg portable_atomic_unstable_f16` are enabled, `AtomicF16` for [unstable `f16`](https://github.com/rust-lang/rust/issues/116909) is also provided.
- When both Cargo feature `float` and unstable `--cfg portable_atomic_unstable_f128` are enabled, `AtomicF128` for [unstable `f128`](https://github.com/rust-lang/rust/issues/116909) is also provided.
Note that unstable cfgs are outside of the normal semver guarantees and minor or patch versions of portable-atomic may make breaking changes to them at any time.

Support AtomicF16/AtomicF128 under unstable cfgs

---

.github/.cspell/project-dictionary.txt
.github/workflows/ci.yml
README.md
src/imp/atomic128/mod.rs
src/imp/atomic128/powerpc64.rs
src/imp/detect/README.md
src/imp/detect/aarch64_illumos.rs
src/imp/detect/powerpc64_aix.rs
src/imp/fallback/mod.rs
src/imp/mod.rs
src/lib.rs
tools/build.sh

Follow-up to #90 
Run-time detection on this platform is currently disabled by default as experimental because I don't yet have an environment where I can run tests.

detect: Support run-time detection on powerpc64 AIX

---

.github/.cspell/project-dictionary.txt
README.md
build.rs
src/imp/atomic128/aarch64.rs
src/imp/detect/aarch64_aa64reg.rs
src/imp/detect/aarch64_apple.rs
src/imp/detect/common.rs
src/imp/float/aarch64.rs
src/imp/float/int.rs
src/imp/float/mod.rs
src/lib.rs
tools/build.sh

Armv9.6 added atomic float instructions for binary{16,32,64} and bfloat16 as FEAT_LSFE (Large System Float Extension).
This PR optimizes AArch64 {16,32,64}-bit atomic float add/sub/max/min when FEAT_LSFE is enabled.
LLVM's assembly support for FEAT_LSFE needs LLVM 20 (https://github.com/llvm/llvm-project/commit/67ff5ba9af9754261abe11d762af11532a816126), so use .inst directive on LLVM 19 or older.
Run-time detection is also implemented, but at this time it is only used in testing. AFAIK no CPUs actually implement this feature yet, so we will only refer to the feature available at compile time at this time.

aarch64: Support FEAT_LSFE
